name: Mirror to GitLab

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}        # Your GitHub PAT stored as GH_PAT
      GITHUB_USER: "mao1910,le-fork"             # GitHub usernames/orgs
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}  # Your GitLab PAT
      GITLAB_GROUP_ID: ${{ secrets.GITLAB_GROUP_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Mirror repositories to GitLab
        run: python mirror_repos.py
