name: Prune stale GitLab projects

on:
  workflow_dispatch:          # Manual trigger
  schedule:
    - cron: '0 3 * * 0'        # Optional: run weekly Sunday at 03:00 UTC

jobs:
  prune:
    runs-on: ubuntu-latest

    env:
      GH_PAT:             ${{ secrets.GH_PAT }}
      GITHUB_TOKEN:       ${{ secrets.GH_PAT }}         # alias for the script
      GITLAB_TOKEN:       ${{ secrets.GITLAB_TOKEN }}
      GITLAB_GROUP_ID:    ${{ secrets.GITLAB_GROUP_ID }}
      GITHUB_USER:        "mao1910,le-fork"            # same as mirror job
      PRUNE_EXCLUDE:      ${{ secrets.PRUNE_EXCLUDE }}   # e.g., mirror-scripts
      DRY_RUN:            "true"                        # change to "false" to delete
      GRACE_DAYS:         "7"                           # days to wait before deletion

    steps:
      - uses: actions/checkout@v3

      - name: Restore prune state cache
        uses: actions/cache@v3
        with:
          path: prune_state.json
          key: prune-state

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Dry-run prune
        run: python prune_repos.py

      - name: Save prune state cache
        uses: actions/cache@v3
        with:
          path: prune_state.json
          key: prune-state
